services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: task_manager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  app:
    build: .
    command: sh -c "python manage.py migrate --noinput && python -m pytest -vv"
    environment:
      DJANGO_SETTINGS_MODULE: task_manager.settings
      ALLOWED_HOSTS: "webserver,localhost,127.0.0.1"
      PYTHONUNBUFFERED: 1
      DATABASE_URL: "postgres://postgres:postgres@db:5432/task_manager"
    depends_on:
      - db

  webserver:
    build: .
    command: bash -c "python manage.py migrate --noinput && python manage.py webserver 0.0.0.0:9000"
    environment:
      DJANGO_SETTINGS_MODULE: task_manager.settings
      ALLOWED_HOSTS: "*"
      PYTHONUNBUFFERED: 1
    ports:
      - "9000:9000"
    depends_on:
      - db

    
    volumes:
      - .:/project
